version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000
    environment:
      VIRTUAL_HOST: ${WEB_HOST}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${WEB_HOST}
      LETSENCRYPT_MAIL: ${LETSENCRYPT_MAIL}
  webhook:
    restart: unless-stopped
    image: staticfloat/docker-webhook
    ports:
      - 8000
    volumes:
      # Mount this code into /code
      - ./:/code
      # Mount the docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      WEBHOOK_HOOKS_DIR: /code/hooks
      WEBHOOK_BRANCH_LIST: master
      VIRTUAL_HOST: ${WEHBOOK_HOST}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${WEHBOOK_HOST}
      LETSENCRYPT_MAIL: ${LETSENCRYPT_MAIL}

networks:
   default:
     external:
       name: webproxy