version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000
    environment:
      VIRTUAL_HOST: ${WEB_HOST}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${WEB_HOST}
      LETSENCRYPT_MAIL: ${LETSENCRYPT_MAIL}

networks:
   default:
     external:
       name: webproxy